### ISSUE TITLE
解决没有acados库的问题

### ISSUE THREAD

**Issue by Charlie0329** [WeiJiLab/openpilot-rootfs#11]
Traceback (most recent call last):
  File "./manager.py", line 203, in <module>
    main()
  File "./manager.py", line 171, in main
    manager_prepare()
  File "./manager.py", line 100, in manager_prepare
    p.prepare()
  File "/data/openpilot/selfdrive/manager/process.py", line 233, in prepare
    importlib.import_module(self.module)
  File "/home/lito/.pyenv/versions/3.8.10/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 18, in <module>
    from selfdrive.controls.lib.lateral_planner import CAMERA_OFFSET
  File "/data/openpilot/selfdrive/controls/lib/lateral_planner.py", line 5, in <module>
    from selfdrive.controls.lib.lateral_mpc_lib.lat_mpc import LateralMpc
  File "/data/openpilot/selfdrive/controls/lib/lateral_mpc_lib/lat_mpc.py", line 13, in <module>
    from selfdrive.controls.lib.lateral_mpc_lib.c_generated_code.acados_ocp_solver_pyx import AcadosOcpSolverCython  # pylint: disable=no-name-in-module, import-error
ImportError: libacados.so: cannot open shared object file: No such file or directory

**Comment by Charlie0329** [comment]
修改1（失败）
修改SConstruct，当arch==aarch64时，修改lenv[LD_LIBRARY_PATH]，重新build Docker image，重新生成rootfs
